// Future Store — catálogo de prueba. Productos reales SONOFF (sonoff.tech),
// revendidos e instalados por Future Store en Perú. Precios en soles (S/).
window.FS_CATALOG = {
  categories: [
    { id: 'paneles',     name: 'Paneles de control', orb: 'multi' },
    { id: 'interruptores', name: 'Interruptores',     orb: 'tap'   },
    { id: 'enchufes',    name: 'Enchufes',            orb: 'tap'   },
    { id: 'sensores',    name: 'Sensores',            orb: 'swipe' },
    { id: 'clima',       name: 'Clima y agua',        orb: 'hold'  },
    { id: 'hubs',        name: 'Hubs y red',          orb: 'multi' },
  ],
  products: [
    // ---- Paneles de control ----
    { id: 'nspanel-pro-gen2', cat: 'paneles', name: 'NSPanel Pro Gen2', model: 'NSPanel Pro Gen2',
      tagline: 'Panel táctil con relé dual, Matter Bridge y hub Zigbee integrados.',
      protocol: 'Matter · Zigbee', price: 449, oldPrice: 499, badge: 'Pre-venta',
      img: 'https://sonoff.tech/cdn/shop/files/NSPanel_Pro_Gen2-10off.avif?v=1777348447&width=800' },
    { id: 'nspanel-pro-120', cat: 'paneles', name: 'NSPanel Pro 120', model: 'NSPanel Pro · 120',
      tagline: 'Centro de control de escenas y dispositivos, pantalla tipo 120.',
      protocol: 'Wi-Fi · Zigbee', price: 429, oldPrice: 499, badge: 'Más vendido',
      img: 'https://sonoff.tech/cdn/shop/files/NS_PRO.avif?v=1775096646&width=800' },

    // ---- Interruptores ----
    { id: 'mini-dim', cat: 'interruptores', name: 'MINI Extreme Dimmer', model: 'MINI-DIM',
      tagline: 'Regulador de intensidad compacto, sin neutro requerido.',
      protocol: 'Matter · Wi-Fi', price: 109,
      img: 'https://sonoff.tech/cdn/shop/files/MINI-DIM_Main_2286352d-286c-480d-a98c-7e858a9c30ae.avif?v=1772594482&width=800' },
    { id: 'mini-zb2gs', cat: 'interruptores', name: 'MINI DUO 2 canales', model: 'MINI-ZB2GS',
      tagline: 'Doble canal para controlar dos circuitos de forma independiente.',
      protocol: 'Zigbee', price: 75,
      img: 'https://sonoff.tech/cdn/shop/files/MINI-ZB2GS_Main_64f48068-3967-4ec8-9d52-671fad74f283.avif?v=1772594118&width=800' },
    { id: 'zbminir2', cat: 'interruptores', name: 'ZBMINI Extreme', model: 'ZBMINIR2',
      tagline: 'El interruptor empotrable más pequeño, ideal para retrofit.',
      protocol: 'Zigbee', price: 55, badge: 'Más vendido',
      img: 'https://sonoff.tech/cdn/shop/files/ZBMINIR2_Main_ba021255-08b3-4170-9b64-622fd22a561a.avif?v=1772594747&width=800' },
    { id: 'm5-matter', cat: 'interruptores', name: 'SwitchMan M5', model: 'M5 · Matter',
      tagline: 'Interruptor de pared premium con botón mecánico y app.',
      protocol: 'Matter · Wi-Fi', price: 79, oldPrice: 85,
      img: 'https://sonoff.tech/cdn/shop/files/m5_matter_c83ab8d1-6bc6-47ff-bc34-6291740bcb49.jpg?v=1769499668&width=800' },
    { id: 'mini-zbrbs', cat: 'interruptores', name: 'Interruptor de persianas', model: 'MINI-ZBRBS',
      tagline: 'Control inteligente de cortinas y persianas motorizadas.',
      protocol: 'Zigbee', price: 69,
      img: 'https://sonoff.tech/cdn/shop/files/MINI-ZBRBS_Main_28580672-c538-4e16-9747-2542323dbbd9.avif?v=1772593620&width=800' },

    // ---- Enchufes ----
    { id: 's61s-outdoor', cat: 'enchufes', name: 'iPlug S61s Exterior', model: 'S61STPF-PM-O',
      tagline: 'Enchufe exterior resistente al agua con medición de energía.',
      protocol: 'Matter · Wi-Fi', price: 82,
      img: 'https://sonoff.tech/cdn/shop/files/S61STPF-PM-O_main.avif?v=1777519625&width=800' },
    { id: 's61s-gen2', cat: 'enchufes', name: 'iPlug Gen2 S61s', model: 'S61STPF',
      tagline: 'Enchufe inteligente con monitoreo de consumo en tiempo real.',
      protocol: 'Matter · Wi-Fi', price: 42, badge: 'Oferta',
      img: 'https://sonoff.tech/cdn/shop/files/S61STPF-_main.avif?v=1777519624&width=800' },
    { id: 's60-zigbee', cat: 'enchufes', name: 'iPlug Zigbee S60', model: 'S60ZB',
      tagline: 'Enchufe Zigbee fácil de integrar a cualquier escena.',
      protocol: 'Zigbee', price: 62,
      img: 'https://sonoff.tech/cdn/shop/files/S60ZB.jpg?v=1751264859&width=800' },

    // ---- Sensores ----
    { id: 'snzb-06p24', cat: 'sensores', name: 'SenseGuard Presencia 24GHz', model: 'SNZB-06P24',
      tagline: 'Detección de presencia humana de alta precisión con radar 24GHz.',
      protocol: 'Zigbee', price: 99, badge: 'Nuevo',
      img: 'https://sonoff.tech/cdn/shop/files/SNZB-06P24-1.avif?v=1779673532&width=800' },
    { id: 'snzb-04pr2', cat: 'sensores', name: 'SenseGuard Puerta/Ventana', model: 'SNZB-04PR2',
      tagline: 'Sensor de apertura ultracompacto para puertas y ventanas.',
      protocol: 'Zigbee', price: 58,
      img: 'https://sonoff.tech/cdn/shop/files/SNZB-04PR2-MAIN.jpg?v=1769655463&width=800' },
    { id: 'snzb-02dr2', cat: 'sensores', name: 'AirGuard TH · LCD 3.6"', model: 'SNZB-02DR2',
      tagline: 'Sensor de temperatura y humedad con pantalla LCD.',
      protocol: 'Zigbee', price: 62,
      img: 'https://sonoff.tech/cdn/shop/files/main-snzb-02dr2.avif?v=1778492637&width=800' },
    { id: 'snzb-02p', cat: 'sensores', name: 'Sensor Temp. y Humedad', model: 'SNZB-02P',
      tagline: 'Monitoreo preciso de clima interior, batería de larga duración.',
      protocol: 'Zigbee', price: 69,
      img: 'https://sonoff.tech/cdn/shop/files/SNZB-02P_dad3f396-6614-4c62-9589-c16623d3318b.avif?v=1778493234&width=800' },
    { id: 'snzb-06p', cat: 'sensores', name: 'Sensor de Presencia', model: 'SNZB-06P',
      tagline: 'Detecta presencia humana para automatizar luces y escenas.',
      protocol: 'Zigbee', price: 75,
      img: 'https://sonoff.tech/cdn/shop/files/SNZB-06P.jpg?v=1751266528&width=800' },

    // ---- Clima y agua ----
    { id: 'hydro-duo', cat: 'clima', name: 'Hydro DUO Válvula de agua', model: 'SWV-ZF2E',
      tagline: 'Válvula de riego de doble canal con medidor de flujo y latón.',
      protocol: 'Zigbee', price: 169, oldPrice: 189, badge: 'Pre-venta',
      img: 'https://sonoff.tech/cdn/shop/files/hydro_duo_main_10off.avif?v=1778221952&width=800' },
    { id: 'sawf-08p', cat: 'clima', name: 'AirGuard CO₂', model: 'SAWF-08P',
      tagline: 'Monitor de calidad de aire con medición de CO₂ vía Matter.',
      protocol: 'Matter · Wi-Fi', price: 199,
      img: 'https://sonoff.tech/cdn/shop/files/main_sawf-08p_1600_1600.jpg?v=1765781120&width=800' },
    { id: 'trvzb', cat: 'clima', name: 'Válvula termostática', model: 'TRVZB',
      tagline: 'Control inteligente de radiadores, ahorra energía en calefacción.',
      protocol: 'Zigbee', price: 115, oldPrice: 155, badge: 'Oferta',
      img: 'https://sonoff.tech/cdn/shop/files/TRV.png?v=1751008560&width=800' },

    // ---- Hubs y red ----
    { id: 'dongle-m', cat: 'hubs', name: 'Dongle Max PoE', model: 'Dongle-M',
      tagline: 'Gateway Zigbee/Thread con PoE para Home Assistant y más.',
      protocol: 'Zigbee · Thread', price: 169,
      img: 'https://sonoff.tech/cdn/shop/files/Dongle-Mmain.jpg?v=1757905881&width=800' },
    { id: 'zbbridge-u', cat: 'hubs', name: 'Zigbee Bridge Ultra', model: 'ZBBridge-U',
      tagline: 'Puente Zigbee de alto alcance para toda tu casa inteligente.',
      protocol: 'Zigbee', price: 399,
      img: 'https://sonoff.tech/cdn/shop/files/Zigbee_Bridge_Ultra.jpg?v=1751515032&width=800' },
  ],
};
