// Future Store mock catalog. All Peruvian Sol pricing.
window.FS_DATA = {
  categories: [
    { id: 'iluminacion', name: 'Iluminación',   sub: 'Focos · ambientes · tiras LED',     orb: 'tap',   count: 32 },
    { id: 'seguridad',   name: 'Seguridad',     sub: 'Cámaras · cerraduras · sensores',   orb: 'multi', count: 28 },
    { id: 'audio',       name: 'Audio y voz',   sub: 'Parlantes · asistentes',            orb: 'swipe', count: 19 },
    { id: 'clima',       name: 'Climatización', sub: 'Termostatos · purificadores',       orb: 'hold',  count: 14 },
    { id: 'energia',     name: 'Energía',       sub: 'Enchufes · medidores · paneles',    orb: 'tap',   count: 21 },
    { id: 'hub',         name: 'Hubs y red',    sub: 'Routers · gateways · Matter',       orb: 'multi', count: 11 },
  ],
  products: [
    { id: 'p1', cat: 'iluminacion', name: 'Hub de Iluminación Aurora',
      tagline: 'Hasta 50 focos · escenas guardadas',
      price: 549, oldPrice: 649, badge: 'Más vendido', orb: 'tap', stock: 12 },
    { id: 'p2', cat: 'seguridad',   name: 'Cerradura Inteligente Lumo',
      tagline: 'Huella · NFC · app · invitados',
      price: 899, badge: 'Nuevo', orb: 'multi', stock: 7 },
    { id: 'p3', cat: 'seguridad',   name: 'Cámara Exterior Vigia 2K',
      tagline: 'Visión nocturna · detección IA',
      price: 459, orb: 'swipe', stock: 22 },
    { id: 'p4', cat: 'audio',       name: 'Parlante de Sala Onda',
      tagline: 'Audio espacial · asistente integrado',
      price: 729, orb: 'hold', stock: 9 },
    { id: 'p5', cat: 'clima',       name: 'Termostato Inteligente Brisa',
      tagline: 'Aprende tus rutinas · ahorra 18% energía',
      price: 369, badge: '−15%', orb: 'tap', stock: 18 },
    { id: 'p6', cat: 'energia',     name: 'Enchufe Smart Pulse · pack 4',
      tagline: 'Wi-Fi · medidor de consumo',
      price: 159, orb: 'multi', stock: 35 },
    { id: 'p7', cat: 'hub',         name: 'Hub Central Matter+',
      tagline: 'Compatible con todas las marcas',
      price: 459, orb: 'multi', stock: 14 },
    { id: 'p8', cat: 'iluminacion', name: 'Tira LED Halo · 5 m',
      tagline: 'RGB · sincroniza con TV',
      price: 189, orb: 'swipe', stock: 28 },
  ],
};
